from mesa import Agent, Model
from mesa.time import RandomActivation # Mesa.time handles the time component of the model. I contains schedulers that handles agent activations. RandomActivation is a scheduler that activates each agent once per step, in random order with order reshuffled every step
from mesa.datacollection import DataCollector # DataCollector is a standard way to collect data generated by a Mesa model. They can be modellevel data, agent-level data and tables
import random
import numpy as np
from matplotlib.pyplot import *
import random
import pandas as pd
import time





class Config:
    def __init__(self, num_agents, dr_num):
        self.trade_percent_all = []
        self.water_held_all_s = []
        self.water_held_all_b = []
        self.water_allow_all_s = []
        self.water_allow_all_b = []
        self.av_all_s = []
        self.av_all_b = []

        self.gft_all_old = []
        self.gft_all_new = []

        self.num_agents = num_agents
        self.dr_num = dr_num
        self.perc_sellers = dr_num / num_agents
        self.dr_severity = 1 - self.perc_sellers

        self.gft_tot_old = []
        self.gft_tot_new = []
        self.trade_percent = []
        self.water_held_tot_b = []
        self.water_allow_tot_b = []
        self.water_held_tot_s = []
        self.water_allow_tot_s = []
        self.av_tot_s = []
        self.av_tot_b = []



def compute_price(model):
	agent_price = [agent.price1 for agent in model.schedule.agents]
	return agent_price