name: Mirror Main Branch to Public Repo

on:
  push:
    branches:
      - main  # Triggers the action whenever there’s a push to main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to public repository
        env:
          PUBLIC_REPO: https://github.com/jgifford01/WaterMarket_ABM.git
          PAT: ${{ secrets.PAT_PUBLIC_REPO }}
        run: |
          git remote add public https://jgifford01:${PAT}@github.com/jgifford01/WaterMarket_ABM.git
          git push -u public main --force
